config/routes.rb
CoolSpots::Application.routes.draw do
  resources :spots, :stats, :guides, :users, :locations
  
  root to: 'welcome#index'
  
  match '/logout', to: 'sessions#destroy'
end

app/models/guide.rb
class Guide < ActiveRecord::Base
  attr_accessible :name, :user_id, :location_id, :votes_count
  belongs_to :user
  belongs_to :location
  
  has_many :votes, as: :voteable
  
  has_many :guide_spots
  has_many :spots, through: :guide_spots

  def self.random
    all.sample
  end
  
end

app/models/guide_spot.rb
class GuideSpot < ActiveRecord::Base
  attr_accessible :guide_id, :spot_id
  belongs_to :guide
  belongs_to :spot, counter_cache: :spots_count
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :city, :country, :name, :region, :user_id
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  attr_accessible :name, :phone, :address, :city, :postcode, :photo, :user_id, :description, :votes_count
  mount_uploader :photo, SpotUploader
  
  belongs_to :user
  
  has_many :guides, through: :guide_spots
  has_many :guide_spots
  has_many :votes, as: :voteable
  
  after_save :ping_guides
  
  
  def ping_guides
    guides.each {|guide| guide.touch }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  has_many :spots
  has_many :guides
end

app/models/vote.rb
class Vote < ActiveRecord::Base  
  attr_accessible :voteable_id, :user_id, :voteable_type
  belongs_to :voteable, polymorphic: true, counter_cache: :votes_count
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_filter :profiler
  
  def profiler
    Rack::MiniProfiler.authorize_request
  end
  
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController

  def index
    @guides = Guide.limit(100).includes(:spots, :user).select("spots.name")
  end

  # GET /guides/1
  # GET /guides/1.json
  def show    
    @guide = Guide.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guide }
    end
  end

  # GET /guides/new
  # GET /guides/new.json
  def new
    @guide = Guide.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guide }
    end
  end

  # GET /guides/1/edit
  def edit
    @guide = Guide.find(params[:id])
  end

  # POST /guides
  # POST /guides.json
  def create
    @guide = Guide.new(params[:guide])

    respond_to do |format|
      if @guide.save
        format.html { redirect_to @guide, notice: 'Guide was successfully created.' }
        format.json { render json: @guide, status: :created, location: @guide }
      else
        format.html { render action: "new" }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guides/1
  # PUT /guides/1.json
  def update
    @guide = Guide.find(params[:id])

    respond_to do |format|
      if @guide.update_attributes(params[:guide])
        format.html { redirect_to @guide, notice: 'Guide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guides/1
  # DELETE /guides/1.json
  def destroy
    @guide = Guide.find(params[:id])
    @guide.destroy

    respond_to do |format|
      format.html { redirect_to guides_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    logout
    redirect_to root_path
  end
  
  def login_links
    
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  before_filter :require_login_from_http_basic, :except => [:show]
  def index
    @spots = current_user.spots

    respond_to do |format|
      format.html # index.html.erb
      format.json {
        spots = @spots.collect {|spot| {caption: spot.name, id: spot.id, preview_url: spot.photo_url, url: "/spots/#{spot.id}"} }
        render json: spots
      }
    end
  end

  def show    
    @spot = Spot.find(params[:id])
    # expires_in 10.seconds, :public => true
    # fresh_when @spot
  end

  def new
    @spot = Spot.new
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def create
    @spot = Spot.new(params[:spot])
    if @spot.save
      redirect_to @spot, notice: 'Spot was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @spot = Spot.find(params[:id])

    if @spot.update_attributes(params[:spot])
      redirect_to @spot, notice: 'Spot was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to spots_url 
  end
  
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  
  def index
    
    # Create a histogram for 0 to 20 milliseconds range, and 2ms-sized bins
    histogram = Aggregate.new(0,20,2)
    
    File.read(File.dirname(__FILE__)+"/../../log/sauspiel.log").split("\n").each do |line|
      #histogram << line.scan(/\W(\d)ms/.first.to_i if line =~ /Completed 200/
    end
    
    @bins = []
    @values = []
    
    histogram.each do |bin, count|
      @bins << bin
      @values << count
    end
    
    @ranges = 0.step(response_times.max, bin_width).each_cons(2).map { |s, e| Range.new(s, e, true) }
    
    @chart_values = response_times.group_by { |v| @ranges.find { |r| r.cover? v } }
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @guide = Guide.random
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip Devise :timeout and :timedout flags
      next if type == :timeout
      next if type == :timedout
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?
      type = :success if type == :notice
      type = :error   if type == :alert
      text = content_tag(:div,
               content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
               message, :class => "alert fade in alert-#{type}")
      flash_messages << text if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/guides/index.html.erb
<div class="span12">
<% @guides.each do |guide| %>
  <h2><%= link_to guide.name, guide_path(guide) %></h2>
  <div class="row">
    <div class="span2">
      <%= link_to image_tag(guide.spots.first.photo_url, style: "border: 3px solid #bbb"), guide_path(guide) %>
    </div>
    <div class="span8">
      <p><%= guide.spots.count %> Spots</p>
      <p style="color: #777">added by <%= link_to guide.user.username, user_path(guide.user) %>, <%= guide.user.guides.count %> guides, <%= guide.user.spots.count %> spots</p>
      <p><%= guide.votes.count %> Votes</p>
    </div>
  </div>
  <div class="row" style="margin-top: 10px">
    <%= render guide.spots %>
  </div>
<% end %>
</div>

app/views/guides/show.html.erb
<div class="span12">
<h2 style="margin-bottom: 20px"><%= @guide.name %></h2>
<h3><%= @guide.votes.count %> votes</h3>
<% @guide.spots.each do |spot| %>
<div class="row" style="margin-bottom: 20px">
  <div class="span2">
  <%= image_tag spot.photo_url, width: 200 %>
  </div>
  <div class="span8">
    <h3 style="line-height: 0; margin-bottom: 15px; font-size: 110%"><%= link_to spot.name, spot_path(spot) %></h3>
    <p style="font-size: 80%">Added by <%= spot.user.username %></p>
    <p style="font-size: 80%"><%= spot.votes.count %> votes</p>
  </div>
</div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CoolSpots" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application", :async => true %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">CoolSpots</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Guides", guides_path %></li>
              <li><%= link_to "My Spots", spots_path %></li>
            </ul>
            <div class="pull-right">
              <% if logged_in? %>
              Welcome <%= current_user.username %> | <%= link_to 'sign out', logout_path %>
              <% else %>

              <% end %>
            </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" style="margin-top: 40px">
        <%= bootstrap_flash %>
        <%= yield %>
    </div> <!-- /container -->
    <footer style="padding: 20px; text-align: center">CoolSpots</footer>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :region %><br />
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class="span12">
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>Country</th>
    <th>Region</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
    <td><%= location.city %></td>
    <td><%= location.country %></td>
    <td><%= location.region %></td>
    <td><%= location.user_id %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>
</div>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>City:</b>
  <%= @location.city %>
</p>

<p>
  <b>Country:</b>
  <%= @location.country %>
</p>

<p>
  <b>Region:</b>
  <%= @location.region %>
</p>

<p>
  <b>User:</b>
  <%= @location.user_id %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/spots/_form.html.erb
<%= bootstrap_form_for @spot do |f| %>
<%= f.text_field :name %>
<%= f.text_field :address %>
<%= f.text_field :city %>
<%= f.text_field :phone %>
<%= f.file_field :photo %>
<%= f.submit %>
<% end %>

app/views/spots/_spot.html.erb
<div class="span1"><%= link_to image_tag(spot.photo_url, width: 80), spot_path(spot) %><br /><%= spot.name %></div>

app/views/spots/edit.html.erb
<h1>Editing spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
<div class="span12">
<% @spots.each do |spot| %>
<h2><%= link_to spot.name, spot_path(spot) %></h2>
<div class="row">
<div class="span2">
  <%= image_tag spot.photo_url, width: 200 %>
</div>
  <div class="span7">
    
    <%= truncate(spot.description, length: 200) %>
  </div>
</div>
<% end %>
</div>

app/views/spots/new.html.erb
<%= render 'form' %>

app/views/spots/show.html.erb
<div class="span3" style="padding-top: 15px">
  <%= image_tag @spot.photo_url, :width => 400 %><br />
  <p style="margin-top: 8px">Added by <%= @spot.user.first_name %></p>
</div>
<div class="span7">
  <h1><%= @spot.name %></h1>
  
  <%= @spot.description %>
</div>

app/views/stats/index.html.erb
<%= @ranges%>
<div id="chart"></div>
<script>
var chart;
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'chart',
                defaultSeriesType: 'column',
                borderWidth:0,
                borderColor:'#ccc',
            },
            credits:{
                enabled:false
            },
            title: {
                text: '',
            },
            tooltip: {
                borderWidth:1,
                formatter: function() {
                        return '<b>Range:</b><br/> '+ this.x +'<br/>'+
                         '<b>Count:</b> '+ this.y;
                }
            },
            plotOptions: {
                series: {
                    shadow: false,
                    borderWidth:1,
                    borderColor:'#c0c0c0',
                    pointPadding:0,
                    groupPadding:0,
                }
            },
            legend: {
                enabled:false
            },
            xAxis: {
                categories: <%=raw @chart_values.keys.collect{|k| k.to_s}.to_s %>,
                labels:{
                    style: {
                        fontSize:'8px',
                        fontWeight:'normal'
                    },
                },
                lineColor:'#444',
                tickLength:5,
                tickColor:'#ccc',
                
            },
            yAxis:{
                title:{
                    text:''
                },
                maxPadding:0,
                gridLineColor:'#e9e9e9',
                tickWidth:1,
                tickLength:3,
                tickColor:'#ccc',
                lineColor:'#ccc',
                endOnTick:false,
                tickInterval:50},
            series: [{
                data: <%= @chart_values.values.collect {|vals| vals.size }.to_s %>,
                color: '#ccc'
            }]
        });
</script>

app/views/welcome/index.html.erb
<div style="margin-top:20px; margin-bottom: 20px" class="row">
<p style="font-size: 180%" class="span12">Make fun guides for your friends when they visit town!</p>
</div>
<div class="row">  
<div class="span4">
<div id="carousel" class="carousel slide">
  <div class="carousel-inner">
    <% @guide.spots.each_with_index do |spot, index| %>
    <div class="item <%= 'active' if index == 0 %>">
    <%= image_tag(spot.photo_url) %>
      <div class="carousel-caption">
       <h4><%= link_to spot.name %></h4>
       <p><%= truncate(spot.description) %></p>
      </div>
    </div>
    <% end %>
  </div>
</div>  
<script async>$('.carousel').carousel()</script>
</div>
<div class="span6">
  <h2 style="font-size: 150%; margin-top: -10px">Featured guide</h2> <h3><%= link_to @guide.name, guide_path(@guide) %></h3>
  <h4>by <%= link_to @guide.user.username, user_path(@guide.user) %></h4>
  <p><% @guide.description %></p>
</div>
</div>